.ORIG X3000

;START BY PRINTING PROMPT TO USER
START
LEA R0, INPUT_PROMPT
PUTS

;GET ADDRESS OF PASSWORD
LEA R2, PASSWORD
AND R4, R4, #0

;COUNT CHARS IN PASSWORD UNTIL WE HIT 0
COUNT_LOOP
LDR R0, R2, #0
BRz FINISH_COUNT
ADD R4, R4, #1
ADD R2, R2, #1
BRnzp COUNT_LOOP

FINISH_COUNT
LEA R2, PASSWORD
ST R4, PASSWORD_COUNT
AND R4, R4, #0
AND R3, R3, #0

;GET EACH CHARACTER
GET_CHARACTER_LOOP
GETC
OUT
ADD R1, R0, #-10        ;CHECK IF ENTER WAS TYPED
BRz ENTER_DETECTED

;COMPARE CHAR TO CHAR IN STRING
LDR, R1, R2, #0     ;LOAD NEXT CHAR FROM PASSWORD
NOT R1, R1
ADD R1, R1, #1      ;MAKE IT NEGATIVE

ADD R2, R2, #1      ;POINT R2 TO NEXT CHAR IN PASSWORD

;SUBTRACT 1 FROM STRING LEGTH TO MAKE IT 0 AT THE END
ADD R4, R4, #1     ;TRACK CHARS USER TYPES IN
ADD R1, R0, R1      ;ADD IT TO CHAR FROM USER
BRz CORRECT_DETECTED



AND R3, R3, #0
ADD R3, R3, #1      ;SET R3 TO 1 IF INCORRECT DETECTED

CORRECT_DETECTED
BRnzp GET_CHARACTER_LOOP

ENTER_DETECTED
ADD R4, R4, #0
LD R0, PASSWORD_COUNT
NOT R0, R0
ADD R0, R0, #1
ADD R
ADD R3, R3, R4
BRz LOGIN_SUCCESSFUL
LEA R0, INCORRECT_PROMPT
PUTS
BRnzp START

LOGIN_SUCCESSFUL
LEA R0, CORRECT_PROMPT
PUTS

HALT

PASSWORD .STRINGZ "ABCD1234"
PASSWORD_COUNT .FILL #0
INPUT_PROMPT .STRINGZ "Please enter your password:"
INCORRECT_PROMPT .STRINGZ "Login Unsuccessful: Incorrect Password\n"
CORRECT_PROMPT .STRINGZ "Login Successful\n"

.END